[package]
name = "termgram"
version = "0.1.0"
edition = "2024"

[dependencies]
grammers-client = { version = "0.10", features = ["fs", "markdown", "html"] }
grammers-mtsender = "0.10"
grammers-session = "0.10"
tokio = { version = "1", features = ["full"] }
anyhow = "1"
rpassword = "7"
dirs = "7"
serde = { version = "1", features = ["derive"] }
toml = { version = "1", features = ["serde"] }
libsql = "0.9"